/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  sidebar: [
    {
      type: "doc",
      label: 'Introduction',
      id: "introduction"
    },
    {
      type: "doc",
      label: 'Getting started',
      id: 'getting-started'
    },
    {
      type: "doc",
      label: 'Hello world with IoT',
      id: 'hello-world-with-iot'
    },
    {
      type: "doc",
      label: 'Build your custom app',
      id: 'build-your-custom-app'
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        {
          type: 'doc',
          label: 'Canvas',
          id: 'guides/canvas'
        },
        {
          type: 'category',
          label: 'Project',
          items: [
            {
              type: 'doc',
              label: 'API key',
              id: "guides/project/api-key"
            },
            {
              type: 'doc',
              label: 'Managing a project',
              id: "guides/project/managing-a-project"
            }
          ],
        },
        {
          type: 'category',
          label: 'Auth',
          items: [
            {
              type: 'doc',
              label: 'Register',
              id: "guides/auth/register"
            },
            {
              type: 'doc',
              label: 'Login',
              id: "guides/auth/login"
            },
            {
              type: 'doc',
              label: 'Logout',
              id: "guides/auth/logout"
            },
            {
              type: 'category',
              label: 'Managing user account',
              items: [
                {
                  type: "doc",
                  label: "Update account password",
                  id: "guides/auth/managing-user-account/update-account-password"
                },
                {
                  type: "doc",
                  label: "Update forgotten password",
                  id: "guides/auth/managing-user-account/update-forgotten-password"
                },
                {
                  type: "doc",
                  label: "Update user profile",
                  id: "guides/auth/managing-user-account/update-user-profile"
                }
              ]
            }
          ]
        },
        {
          type: 'category',
          label: 'Devices',
          items: [
            {
              type: "doc",
              label: "Model",
              id: "guides/devices/model"
            },
            {
              type: "doc",
              label: "Data",
              id: "guides/devices/data"
            },
            {
              type: "doc",
              label: "Pairing",
              id: "guides/devices/pairing"
            }
          ],
        },
        {
          type: 'category',
          label: 'Datastore',
          items: [
            {
              type: "doc",
              label: "Overview",
              id: "guides/datastore/overview"
            },
            {
              type: "doc",
              label: "Collections",
              id: "guides/datastore/collections"
            },
            {
              type: "doc",
              label: "Querying",
              id: "guides/datastore/querying"
            }
          ],
        },
        {
          type: 'category',
          label: 'Security',
          items: [
            {
              type: "doc",
              label: "User and administrator",
              id: "guides/security/user-and-administrator"
            },
            {
              type: "doc",
              label: "CORS",
              id: "guides/security/cors"
            },
            {
              type: "doc",
              label: "Access Credentials",
              id: "guides/security/access-credentials"
            }
          ],
        },
        {
          type: 'category',
          label: 'Hardware',
          items: [
            {
              type: "doc",
              label: "Setting up the board",
              id: "guides/hardware/setting-up-the-board"
            },
            {
              type: "doc",
              label: "Handling WiFi",
              id: "guides/hardware/handling-wifi"
            },
            {
              type: "doc",
              label: "Handling Connection Status",
              id: "guides/hardware/handling-connection-status"
            },
            {
              type: "doc",
              label: "Handling Device Variables",
              id: "guides/hardware/handling-device-variables"
            },
            {
              type: "doc",
              label: "Handling Updates",
              id: "guides/hardware/handling-updates"
            }
          ],
        }
      ],
    },
    {
      type: 'category',
      label: 'References',
      items: [
        {
          type: 'category',
          label: 'Device SDK',
          items: [
            {
              type: 'doc',
              label: 'Installation',
              id: 'references/device-sdk/installation'
            },
            {
              type: 'doc',
              label: '.init',
              id: 'references/device-sdk/initialization'
            },
            {
              type: 'doc',
              label: '.isConnected',
              id: 'references/device-sdk/is-connected'
            },
            {
              type: 'doc',
              label: '.onConnection',
              id: 'references/device-sdk/on-connection'
            },
            {
              type: 'category',
              label: 'device',
              items: [
                {
                  type: 'doc',
                  label: 'Overview',
                  id: 'references/device-sdk/device/overview'
                },
                {
                  type: 'category',
                  label: '.data',
                  items: [
                    {
                      type: 'doc',
                      label: '.get',
                      id: 'references/device-sdk/device/data/get'
                    },
                    {
                      type: 'doc',
                      label: '.set',
                      id: 'references/device-sdk/device/data/set'
                    },
                    {
                      type: 'doc',
                      label: '.on',
                      id: 'references/device-sdk/device/data/on'
                    }
                  ]
                }
              ]
            },
            {
              type: 'category',
              label: 'datastore',
              items: [
                {
                  type: 'doc',
                  label: 'Overview',
                  id: 'references/device-sdk/datastore/overview'
                },
                {
                  type: 'category',
                  label: '.collection',
                  items: [
                    {
                      type: 'doc',
                      label: '.insert',
                      id: 'references/device-sdk/datastore/collection/insert'
                    },
                    {
                      type: 'doc',
                      label: '.search',
                      id: 'references/device-sdk/datastore/collection/search'
                    }
                  ]
                }
              ]
            }
          ],
        },
        {
          type: 'category',
          label: 'Client SDK',
          items: [
            {
              type: 'doc',
              label: 'Installation',
              id: 'references/client-sdk/installation'
            },
            {
              type: 'doc',
              label: '.init',
              id: 'references/client-sdk/initialization'
            },
            {
              type: 'doc',
              label: '.isConnected',
              id: 'references/client-sdk/is-connected'
            },
            {
              type: 'doc',
              label: '.onConnection',
              id: 'references/client-sdk/on-connection'
            },
            {
              type: 'category',
              label: 'devices',
              items: [
                {
                  type: 'doc',
                  label: 'Overview',
                  id: 'references/client-sdk/devices/overview'
                },
                {
                  type: 'doc',
                  label: '.get',
                  id: 'references/client-sdk/devices/get'
                },
                {
                  type: 'doc',
                  label: '.count',
                  id: 'references/client-sdk/devices/count'
                },
                {
                  type: 'doc',
                  label: '.on',
                  id: 'references/client-sdk/devices/on'
                },
                {
                  type: 'category',
                  label: '.device',
                  items: [
                    {
                      type: 'doc',
                      label: 'Overview',
                      id: 'references/client-sdk/devices/device/overview'
                    },
                    {
                      type: 'doc',
                      label: '.get',
                      id: 'references/client-sdk/devices/device/get'
                    },
                    {
                      type: 'doc',
                      label: '.set',
                      id: 'references/client-sdk/devices/device/set'
                    },
                    {
                      type: 'doc',
                      label: '.on',
                      id: 'references/client-sdk/devices/device/on'
                    },
                    {
                      type: 'doc',
                      label: '.pair',
                      id: 'references/client-sdk/devices/device/pair'
                    },
                    {
                      type: 'doc',
                      label: '.unpair',
                      id: 'references/client-sdk/devices/device/unpair'
                    },
                    {
                      type: 'category',
                      label: '.data',
                      items: [
                        {
                          type: 'doc',
                          label: '.get',
                          id: 'references/client-sdk/devices/device/data/get'
                        },
                        {
                          type: 'doc',
                          label: '.set',
                          id: 'references/client-sdk/devices/device/data/set'
                        },
                        {
                          type: 'doc',
                          label: '.on',
                          id: 'references/client-sdk/devices/device/data/on'
                        }
                      ]
                    }
                  ]
                }
              ]
            },
            {
              type: 'category',
              label: 'auth',
              items: [
                {
                  type: 'doc',
                  label: 'Overview',
                  id: 'references/client-sdk/auth/overview'
                },
                {
                  type: 'doc',
                  label: '.register',
                  id: 'references/client-sdk/auth/register'
                },
                {
                  type: 'doc',
                  label: '.isAuthenticated',
                  id: 'references/client-sdk/auth/is-authenticated'
                },
                {
                  type: 'doc',
                  label: '.login',
                  id: 'references/client-sdk/auth/login'
                },
                {
                  type: 'doc',
                  label: '.logout',
                  id: 'references/client-sdk/auth/logout'
                },
                {
                  type: 'doc',
                  label: '.forgotPassword',
                  id: 'references/client-sdk/auth/forgot-password'
                },
                {
                  type: 'doc',
                  label: '.changePassword',
                  id: 'references/client-sdk/auth/change-password'
                },
                {
                  type: 'doc',
                  label: '.updateProfile',
                  id: 'references/client-sdk/auth/update-profile'
                },
              ]
            },
            {
              type: 'category',
              label: 'datastore',
              items: [
                {
                  type: 'doc',
                  label: 'Overview',
                  id: 'references/client-sdk/datastore/overview'
                },
                {
                  type: 'doc',
                  label: '.list',
                  id: 'references/client-sdk/datastore/list'
                },
                {
                  type: 'doc',
                  label: '.drop',
                  id: 'references/client-sdk/datastore/drop'
                },
                {
                  type: 'category',
                  label: '.collection',
                  items: [
                    {
                      type: 'doc',
                      label: 'Overview',
                      id: 'references/client-sdk/datastore/collection/overview'
                    },
                    {
                      type: 'doc',
                      label: '.insert',
                      id: 'references/client-sdk/datastore/collection/insert'
                    },
                    {
                      type: 'doc',
                      label: '.search',
                      id: 'references/client-sdk/datastore/collection/search'
                    },
                    {
                      type: 'doc',
                      label: '.update',
                      id: 'references/client-sdk/datastore/collection/update'
                    },
                    {
                      type: 'doc',
                      label: '.delete',
                      id: 'references/client-sdk/datastore/collection/delete'
                    }
                  ]
                }
              ]
            }
          ],
        },
        {
          type: 'category',
          label: 'Canvas',
          items: [
            {
              type: 'doc',
              label: 'Overview',
              id: 'references/canvas/overview'
            },
            {
              type: 'doc',
              label: 'Button',
              id: 'references/canvas/button'
            },
            {
              type: 'doc',
              label: 'Display',
              id: 'references/canvas/display'
            },
            {
              type: 'doc',
              label: 'Progress',
              id: 'references/canvas/progress'
            },
            {
              type: 'doc',
              label: 'Slider',
              id: 'references/canvas/slider'
            },
            {
              type: 'doc',
              label: 'Table',
              id: 'references/canvas/table'
            },
            {
              type: 'doc',
              label: 'Graph',
              id: 'references/canvas/graph'
            }
          ],
        },
        {
          type: 'doc',
          label: 'CLI',
          id: 'references/cli'
        },
        {
          type: 'doc',
          label: 'RestAPI',
          id: 'references/restapi'
        },
        {
          type: 'doc',
          label: 'Response Codes',
          id: 'references/response-codes'
        }
      ],
    },
    {
      type: 'doc',
      label: 'Keywords',
      id: 'keywords'
    },
    {
      type: 'doc',
      label: 'FAQs',
      id: 'faqs'
    }
  ],
};

module.exports = sidebars;
